julia-vscode/StaticLint.jl

- src/StaticLint.jl
- src/bindings.jl
- src/documentserver.jl
I think what I did here is correct, but this is the one PR I'm not just going to merge, because I'm not sure enough about the code :) This PR does work with all the stuff that I merged (and am going to merge in a few minutes).
> Remove global variables

- src/utils.jl
using @8uurg's code from https://github.com/julia-vscode/julia-vscode/issues/849 until I can dig deeper.
> get_root_method safety trip

- src/StaticLint.jl
- src/linting/checks.jl
> Add error for included files that don't exist

- src/StaticLint.jl
- src/server.jl
> Improve get_path logic

- src/StaticLint.jl
- src/linting/checks.jl
- src/server.jl
Where a file (or subsequently included file) includes itself
> safety check for include loops

- src/linting/checks.jl
> check clashing module and submodule names

- src/bindings.jl
- src/linting/checks.jl
- test/runtests.jl
- fixes an instance where short form function names weren't associating with the correct binding
- fix check_modulename
- fixes check_call
> Misc. fixes

- src/server.jl
> handle raw strings in include paths

- Project.toml
- src/bindings.jl
- src/linting/checks.jl
- src/references.jl
- test/runtests.jl
https://github.com/julia-vscode/CSTParser.jl/pull/118, may require version changes
> Handle NONSTDIDENTIFIERs

- src/linting/checks.jl
- src/utils.jl
- test/runtests.jl
> fix `stdcall` missing ref

- src/linting/checks.jl
- test/runtests.jl
> check for equality in if cond

- src/linting/checks.jl
> misc fixes 

- src/linting/checks.jl
- test/runtests.jl
Addresses an issue raised on slack
> test type parameters in pirates check

- src/linting/checks.jl
- test/runtests.jl
https://github.com/julia-vscode/julia-vscode/issues/962
> allow any method call for struct defs modified by macros

- src/references.jl
- src/utils.jl
> Don't use a Set when not needed

- src/macros.jl
I will find time to do a line by line check for accessing of EXPR.args, but a small fix for now
> args access fix, #104

- src/utils.jl
fixes https://github.com/julia-vscode/StaticLint.jl/issues/106
> make _is_in_basedir type stable (String)

- src/bindings.jl
- test/runtests.jl
fix for https://github.com/julia-vscode/julia-vscode/issues/1037
> fix bindings for Flatten EXPR

- src/imports.jl
- src/references.jl
fixes:
https://github.com/julia-vscode/StaticLint.jl/issues/107#event-3108146061
https://github.com/julia-vscode/StaticLint.jl/issues/109
> fix use of PackageRef

- src/imports.jl
> account for package refs pointing to packagerefs

- Project.toml
- src/StaticLint.jl
- src/bindings.jl
- src/imports.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/scope.jl
- src/server.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
Support for SymbolServer changes: https://github.com/julia-vscode/SymbolServer.jl/pull/123/
Note: Will need Project.toml updated for new SymServ version
> symserv update fix

- test/runtests.jl
> Add a root testset

- src/references.jl
> check getfield expr length on resolving

- Project.toml
- src/utils.jl
support for: https://github.com/julia-vscode/SymbolServer.jl/pull/139 . 
Will bump Project.toml ver for SymServ.
Fix for: https://github.com/julia-vscode/julia-vscode/issues/1140
> fix for SymServer exportednames store

- src/bindings.jl
- test/runtests.jl
Closes https://github.com/julia-vscode/julia-vscode/issues/1144
> make sure the binding for inner constructors gets added to parent scope

- src/linting/checks.jl
- test/runtests.jl
> piracy fix

- src/scope.jl
> Fix missing method, add a couple docs

- src/references.jl
- src/utils.jl
> fix resolve_getindex

- src/imports.jl
- test/runtests.jl
> resolve `using` of self

- src/server.jl
> don't try to call joinpath on nothing

- src/linting/checks.jl
- test/runtests.jl
> Add check for unused function arguments

- src/bindings.jl
- src/linting/checks.jl
- src/references.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
> Fix datatype declaration check

- test/runtests.jl
Needs to be updated after typo fix
> Run scopepass on self to hit more code

- src/bindings.jl
- src/imports.jl
- src/linting/checks.jl
- src/utils.jl
- test/runtests.jl
Fixes a couple of bugs:
- issue with import/export of operators
- multiple `where` statements in pirate check
- makes a potential infinite loop into a recursive call
> Misc fixes

- src/imports.jl
> symbol lookup fixes

- src/bindings.jl
- src/linting/checks.jl
Note - Intended to cause errors so will need to be followed up
> remove some while loops, add safety trip to remaining while

- src/linting/checks.jl
- test/runtests.jl
Checks that calls to call and continue are within a loop. Replicates a check within julia-syntax.scm
> check break/continue are in a loop

- src/references.jl
- test/runtests.jl
> fix resolving of dot macro

- src/linting/checks.jl
So that our linter warns on:
- <img width="670" alt="Screen Shot 2020-07-13 at 21 54 21" src="https://user-images.githubusercontent.com/40514306/87306719-6b37d500-c553-11ea-8f9a-5f2cd6b2dcc1.png">
- <img width="670" alt="Screen Shot 2020-07-13 at 21 54 47" src="https://user-images.githubusercontent.com/40514306/87306771-7a1e8780-c553-11ea-9739-607ed707f458.png">
> power up constant redef check

- src/StaticLint.jl
- src/bindings.jl
- src/interface.jl
- test/runtests.jl
Some external functions for running semantic passes on files or strings.
> add external functions

- src/scope.jl
The use of `Expr` was causing an incredible slowdown
> remove use of Expr

- src/bindings.jl
- src/linting/checks.jl
- test/runtests.jl
> fix rem_wheres_decls use

- src/linting/checks.jl
- test/runtests.jl
minor fix for https://github.com/julia-vscode/StaticLint.jl/issues/256#issuecomment-772259684
Wait until after julia-vscode release has been pushed to merge.
> fix sig unwrapping

- src/linting/checks.jl
> check_call  fix (don't match sig against nothing)

- src/linting/checks.jl
> check bincall length

- src/bindings.jl
> binding check

- src/StaticLint.jl
- src/linting/checks.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/8
> Add check for NULL in possible paths

- src/bindings.jl
- src/linting/checks.jl
- src/references.jl
- src/scope.jl
- src/utils.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/913.
> respect soft scope and stop clobbering bindings

- src/utils.jl
> fix loose_refs

- src/linting/checks.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1218
> fix collection of parameters w/o default vals

- src/imports.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/925#issuecomment-818716673
> handle import .. as .. syntax

- src/StaticLint.jl
- src/bindings.jl
> check isid before valofid

- src/linting/checks.jl
> add check for is a EXPR

- src/imports.jl
- test/runtests.jl
https://github.com/julia-vscode/LanguageServer.jl/pull/562 is not yet ready, and until it is, we need to disable this feature.
> Disable workspace packages for now

- src/linting/checks.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2331.
> Fix PointlessAND description

- src/imports.jl
- test/runtests.jl
Fixes #https://github.com/julia-vscode/LanguageServer.jl/issues/974
> hand aliased imports

- src/type_inf.jl
Speculative fix for a stackoverflow error from AZURE
> check assumption

- Project.toml
For https://github.com/julia-vscode/LanguageServer.jl/issues/998
> Release 8.1.1

- src/references.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2657.
> Fix kwarg ref/binding handling

- src/bindings.jl
- test/runtests.jl
Needs https://github.com/julia-vscode/CSTParser.jl/pull/337.
> Properly mark bindings for const-fields in mutable structs

- src/references.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3037
> Fix resolve_getfield for non standard identifiers

- src/StaticLint.jl
and add support for Revise.includet
Fixes https://github.com/julia-vscode/julia-vscode/issues/3229.
> feat: improve followinclude to check ref

- src/linting/checks.jl
It's been in Base since Julia 1.1
> recommend isnothing for comparing against nothing

- .github/workflows/jlpkgbutler-ci-master-workflow.yml
- .github/workflows/jlpkgbutler-ci-pr-workflow.yml
- Project.toml
> Declare compatible with SymbolServer 8
