- Project.toml
Tests still fails with:
```
ERROR: LoadError: EOFError: read end of file
Stacktrace:
[1] read at ./iobuffer.jl:212 [inlined]
[2] read at ./stream.jl:856 [inlined]
[3] deserialize at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.2/Serialization/src/Serialization.jl:722 [inlined]
[4] deserialize(::Base.PipeEndpoint) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.2/Serialization/src/Serialization.jl:709
[5] top-level scope at /Users/kristoffer/.julia/packages/SymbolServer/f6geS/src/clientprocess/clientprocess_main.jl:16
[6] include at ./boot.jl:328 [inlined]
[7] include_relative(::Module, ::String) at ./loading.jl:1094
[8] include(::Module, ::String) at ./Base.jl:31
[9] exec_options(::Base.JLOptions) at ./client.jl:295
[10] _start() at ./client.jl:464
in expression starting at …
```
> add test deps

- src/bindings.jl
- src/imports.jl
- src/macros.jl
- src/references.jl
- src/utils.jl
No need to leave this freely typed (and it's assumed to be a Vector in other packages).
> set Binding refs field type

- src/imports.jl
- src/references.jl
Previous logic failed (in some places) to include baremodules when checking whether an EXPR defined a module
> fix all typof module checks to include baremodules

- src/macros.jl
- test/runtests.jl
e.g. where documentation is attached to a symbol in advance of a meaningful variable declaration
```julia
""" 
somefunc(a,b)
Some description
"""
somefunc
```
> mark documented symbols

- src/linting/checks.jl
- src/utils.jl
- test/runtests.jl
Simple type piracy check: any method that extends an imported function and does not make use of user declared datatypes in the signature are marked.
> add type piracy check

- src/server.jl
Maybe fixes https://github.com/julia-vscode/StaticLint.jl/issues/68.
But in any case, the old version was incorrect because it would always add a `/` at the front for windows paths, which it shouldn't.
> Fix get_path

- src/references.jl
~30% speedup on a scopepass of `/base`.
> Don't run resolve_ref when not needed

- src/linting/checks.jl
Had the same underlying issue for linting call sites that #48 fixed in the utilities:
There exists a cycle in the graph formed by following only `prev` (or only `next`). This results in an infinite loop, given that prev (or next) is never `nothing`.
> Quick fix for infinite loop when there is a cycle

- src/StaticLint.jl
Fixes #116. Maybe :) I'm not really very familiar with this part of the code.
The main idea here is that `loadfile` can silently fail, so if we take one of the if clauses above that calls `loadfile`, but then that doesn't work (say the file has been deleted between the call to `canloadfile` and the call to `loadfile`) then we currently crash because there is a call to `getfile` later on that assumes that the file is actually loaded into the server.
> Check that file is loaded into server before using it

- src/linting/checks.jl
- test/runtests.jl
Adds warnings for the following situations:
```julia
struct T end
T = 1
```
and
```julia
T = 1
struct T end
```
I've not added a configuration option for this as its more of a 'this will not run' lint
> Add warning of redfinition of constants through type definition

- src/StaticLint.jl
- src/exception_types.jl
- src/server.jl
I looked at bit more at the crash report from https://github.com/julia-vscode/LanguageServer.jl/issues/594, and I think there is some sort of bug in `get_path`. This adds some diagnostics that might help us figure out what is going on.
> Add some diagnostics

- README.md
- docs/src/index.md
- src/server.jl
This seems to be not used anywhere, so we might as well remove it?
There is more coming, we generally need to rethink a bit how we think about paths here because we have a hard assumption baked in that we can construct a path for all files that are opened currently, which is not the case. More PRs to other packages coming :)
> Remove setpath

- src/references.jl
I've tracked down one of the infinite loops which should allow for the removal of the tracking of visited scopes (moved to the function `module_safety_trip`). Removing that call cuts allocations during a scopepass by an order of magnitude but I'm hesitant to do so right now
> add resolve_ref_from_module

- src/StaticLint.jl
- src/references.jl
- src/scope.jl
- src/server.jl
- src/utils.jl
This splits the pass across CST carried out by SL into two distinct stages. First there is a toplevel pass which pushes all delayed scopes (i.e. functions, macros and export statements) to a list which are then resolved afterwards. Importantly, thiis second stage should be able to be done concurrently.
> Split toplevel and delayed passes

- Project.toml
- src/linting/checks.jl
- src/references.jl
- test/runtests.jl
This marks the rhs of getfield (`a.b`) calls as errors where we can determine what fields the lhs should have. 
This is ready to go but has highlighted several issues with how we handle the namespaces of modules imported by a SymbolServer cache. 
Requires https://github.com/julia-vscode/SymbolServer.jl/pull/147, a ver bump on SymServ then updated Project.toml
> Enable missing ref errors for getfields

- src/linting/checks.jl
- test/runtests.jl
Any field of LintOptions set to nothing will be set to default value
This is for fixing https://github.com/julia-vscode/LanguageServer.jl/issues/624
> Add constructor for LintOptions that coalesces nothing

- src/linting/checks.jl
- src/references.jl
Turn on everything by default - if it's in there it should be used and fi it doesn't work for people (literal bugs or just isn't useful) this way we get feedback.
Also fixes a resolve_getfield issue
> turn checks on by default, add missingref options

- src/StaticLint.jl
- src/bindings.jl
- src/macros.jl
- src/references.jl
- src/utils.jl
Explicit handling of `new` (it was previously handled as a keyword in CSTParser which wasn't quite right).
Also some more tidying - should be all cosmetic.
> Explicitly resolve `new` within struct defs

- src/references.jl
- src/type_inf.jl
Removes an infinite loop breaker within the `resolve_ref` mechanism that is (should be) no longer needed. This will need to be tested carefully on the insiders release
> remove infinite loop breaker

- src/bindings.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/utils.jl
- test/runtests.jl
`SymbolServer.VarRef`s are used to point at objects in a SymbolServer cache of a collection of packages. Except where used within `SymbolServer.SymStore` objects, we don't want them exposed elsewhere in StaticLint - this PR removes a few instances where they could be introduced.
Also, a fix for the order in which we iterate over function methods
> Ensure we follow VarRefs to the object they point at

- src/imports.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/utils.jl
- test/runtests.jl
Handles the case where an expression passed to `@eval` introduces a binding. Lifts the binding to the top-level scope.
> Add rudimentary handling for `@eval`

- src/StaticLint.jl
- src/bindings.jl
- src/imports.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/scope.jl
- src/server.jl
- src/utils.jl
- test/runtests.jl
Fixes a number of bugs:
- Improves the handling of method overloading through the use of qualified names (i.e. `Module.func`). Takes proper account of whether the function is exported to the current scope/namespace.
-Resolve exports on demand. Export statements can include variables that are defined later within the code but we still need to calculate what _is_ exported as needed.
-Adds custom handles for `deprecate_binding`.
> Bug fixes: method overloading, import/exports, add macro handler

- Project.toml
- src/linting/checks.jl
- src/utils.jl
- test/runtests.jl
> fic call check (remove surround type info from func sigs)

- src/bindings.jl
This has been hit quite a lot according to azure
> check scope exists before adding a name to it

- src/StaticLint.jl
- src/linting/checks.jl
- test/runtests.jl
Check for `f(a::Int = "not an Int")`. Is restricted to operate on types: (String,Symbol,Int,Float64) for the declarations and where the rhs is a literal
> Check default value of kwargs matches given type

- Project.toml
- src/utils.jl
Simplify interface - only use .exportednames field. Possibly paves the way for removal of the .exported field in the future (which doesn't really make sense to be attached to the object)
> modify isexportedby

- src/linting/checks.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1609.
I'm not sure whether we should special case `@nospecialize` or treat all 1-arg macrocalls in function arguments the same.
> fix nospecialize handling

- src/StaticLint.jl
This makes the linter a bit more conservative (it should only complain if we can actually find a path, not when we give up on finding one) and fixes https://github.com/julia-vscode/julia-vscode/issues/1608.
> fewer false positives in include

- src/linting/checks.jl
- src/macros.jl
- test/runtests.jl
follows #212; this one handles `@nospecialize(val)` form and fixes false positive unused arg reports
> more at-nospecialize handling

- src/linting/checks.jl
Fixes an error on Azure:
```
ErrorException: type Nothing has no field refs 
at getproperty(::Nothing, ::Symbol) (Base.jl33)
at check_farg_unused(::CSTParser.EXPR) (./julialang.language-julia-insider-1.0.10/scripts/packages/StaticLint/src/linting/checks.jl471)
at check_all(::CSTParser.EXPR, ::StaticLint.LintOptions, ::LanguageServerInstance) (./julialang.language-julia-insider-1.0.10/scripts/packages/StaticLint/src/linting/checks.jl93)
at check_all(::CSTParser.EXPR, ::StaticLint.LintOptions, ::LanguageServerInstance) (./julialang.language-julia-insider-1.0.10/scripts/packages/StaticLint/src/linting/checks.jl101)
at lint!(::LanguageServer.Document, ::LanguageServerInstance) (./julialang.language-julia-insider-1.0.10/scripts/packages/LanguageServer/src/staticlint.jl58)
at …
```
> add a nothing-check in check_farg_unused

- src/bindings.jl
- src/imports.jl
Fixes
```
MethodError: no method matching scopehasbinding(::Nothing, ::String)
Closest candidates are:
scopehasbinding(!Matched::StaticLint.Scope, ::String) at c:\Users\...\.vscode\extensions\julialang.language-julia-1.0.10\scripts\packages\StaticLint\src\scope.jl:57 
```
The second commit should fix
```
MethodError: no method matching get_named_toplevel_module(::StaticLint.Scope, ::Nothing)
Closest candidates are:
get_named_toplevel_module(::StaticLint.Scope, !Matched::String) at /Users/.../.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/StaticLint/src/imports.jl:90 
MethodError:
at _get_field(::Dict{Symbol,SymbolServer.ModuleStore}, ::CSTParser.EXPR, ::StaticLint.Toplevel{LanguageServer.Document}) (./julialang.language-julia-1.0.10/scripts/packages/StaticLint/src/impo …
```
> add a nothing-check in isglobal

- src/bindings.jl
- test/runtests.jl
Correctly mark bindings of structs defined with kwdef
> handle `Base.@kwdef`

- src/StaticLint.jl
- src/linting/checks.jl
- src/server.jl
- src/type_inf.jl
- test/runtests.jl
Some extra type inference. 
Finds all the instances where a binding is used as the argument to a function call and then finds the intersect of possible types for that argment position. Only works in fairly simple cases (e.g. no handling for abstract types or unions of types).
Restricted to not run on the top-level scope.
> infer binding types by use

- src/scope.jl
- test/runtests.jl
Adds a binding for `eval` on entry to the top-level or a module scope. Are there other bindings that are automatically included in modules (other than themselves)?
> add eval method that isn't Core.eval

- Project.toml
- src/StaticLint.jl
- src/server.jl
- test/runtests.jl
Adds a new option for `semantic_pass` whereby only 'target' expressions get the full treatment (i.e. build new scopes, add bindings etc) for the rest we only resolve references. The logic isn't fully worked out but the idea is that we'd only run everything on the toplevel scope and those parts of the tree (delayed scope - e.g. functions) that are new - for the rest we only need to ensure that any new bindings that have been added to the toplevel scope are resolved.
> add resolve only pass

- src/StaticLint.jl
- src/bindings.jl
- src/imports.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/scope.jl
- src/server.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
Removes the `prev` and `next` field from `Binding` and replaces them with an approach where only the initial binding for a function/datatype is used - all subsequent methods are stored within that initial binding (e.g. a pseudo method table).  Intended to solve stackoverflow errors when iterating through function methods. 
This is ready - bugs will follow but should be relatively easy to squash and _may_ solve one of our most persistent bugs. Interface change so requires ver bump
> Remove between Binding linkages

- src/references.jl
Trying to get rid of the stackoverflow errors we've been seeing. 
Not sure this will work solve the issue so a  bit of explanation incase someone else wants to have a crack at it:
When resolving a symbol (the 'target') we check to see whether `using`ed modules exports a symbol matching the target's name. Running a pass on :export statements is delayed (i.e. until after the `Toplevel` pass) as they can reference yet to be defined symbols.,Tthis means that when checking whether a module exports a name we need to resolve all symbols in the :export statement (`initial_pass_on_exports`) given what we know at that point of the scope. The stackoverflow is caused by some loop where, when trying to resolve the export statement we're pingponging back between two (or more) modules trying to load the …
> be more careful when trying to resolve  export statements early

- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
References to a Binding as another's `.type` were not being cleaned properly - we had links to CST that had been deleted.
> Clean Binding references more thoroughly

- src/imports.jl
> add get_named_toplevel_module default method

- src/bindings.jl
- src/scope.jl
- test/runtests.jl
Fixes some of https://github.com/julia-vscode/julia-vscode/issues/1922
> stop overwriting struct params

- src/type_inf.jl
- test/runtests.jl
Fixes a bug reported on Slack.
Originally we wouldn't mark the `T` in e.g. `foo(x::T) where T = bar(T)` as having a known type, but the use in the `where` expression guarantees it'll be a `DataType` (or `UnionAll`). This was problematic in case the method body can back-propagate `T`'s type, as would be the case in
```
bar(u::Union) = 1
foo(x::T) where {T} = bar(T)
```
> infer where type param types

- src/StaticLint.jl
- src/imports.jl
- src/linting/checks.jl
- src/references.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
> check for unused bindings

- src/StaticLint.jl
- src/bindings.jl
- src/coretypes.jl
- src/interface.jl
- src/linting/checks.jl
- src/methodmatching.jl
- src/references.jl
- src/server.jl
- src/subtypes.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
- test/typeinf.jl
Adds some rudimentary inference for elements of arrays. 
For type inference by use (i.e. where we infer the type of a variable by the argument slot it sits in in a function call) adds handling for `if` blocks so that the uncertainty of whether a branch is hit is accounted for.
Also adds some internal (as yet unused) functions for reasoning about the specific method being used at a call site. The intention is to use this in combination with function return type cached by SymbolServer to improve our inference. [Note - there are currently two different pieces of code that iterate across function methods (`check_call` and `infer_type_by_use`) and use of the functions referenced above would add a third. These should be combined/rationalised.]
> Type inf improvements

- src/StaticLint.jl
- src/bindings.jl
- src/imports.jl
- src/interface.jl
- src/linting/checks.jl
- src/macros.jl
- src/references.jl
- src/scope.jl
- src/server.jl
- src/type_inf.jl
- src/utils.jl
- test/runtests.jl
Currently has no effect but puts in place a mechnism to allow the server to specify what collection of SymbolStore cached packages are made available to a given file. For LanguageServer this means a workspace with multiple folders (packages) open could have the appropriate environments made available to each (and additional packages for test folders, etc). 
~Not for immediate merging.~
Ready, will require tagging
> add infrastructure for file-specific environments

- src/imports.jl
- test/runtests.jl
Fixes an issue from our crash reporting.
> fix import as linting for incomplete expressions

- src/linting/checks.jl
Fixes false positive in https://github.com/julia-vscode/julia-vscode/issues/2215#issuecomment-878362860
> fix check call for a binding::Function without methods

- src/imports.jl
- src/references.jl
- src/server.jl
- test/runtests.jl
I _think_ this is all that's needed on this side so that `using` statements will point to the 'live' code of packages that is being edited. Alongside the symbolserver store of packages I've added a new `workspacepackages` field which will be checked prior to the symbolserver list. It will be up to the user (e.g. the LanguageServerInstance) to ensure that this list is properly managed, I'll open a PR on the other side to discuss how this is managed.
Todo:
Example code:
```julia
using StaticLint, SymbolServer, CSTParser
using StaticLint: File, FileServer, loadfile, scopepass
server = FileServer(Dict(), Set(), deepcopy(SymbolServer.stdlibs), Dict{String,CSTParser.EXPR}());
f = loadfile(server, String(first(methods(CSTParser.eval)).file))
scopepass(f)
server.workspacepackages["CSTParser"] = …
```
> Allow `using` statements to access packages loaded within workspace

- src/bindings.jl
- src/linting/checks.jl
- test/runtests.jl
for bindings and refs. This shouldn't be too expensive, even though a bit hacky.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2187.
> disable non-at-eval macrocall linting

- src/StaticLint.jl
- src/bindings.jl
- src/linting/checks.jl
- test/runtests.jl
For any assignment this checks that none of its ancestors is an `@.` call before marking a binding. I'm happy to hear any suggestions if there is a better approach.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2514
> Skip bindings for assignments in @.  

- src/linting/checks.jl
- test/runtests.jl
See https://github.com/JuliaLang/julia/pull/43671
> Type declarations on global variables are supported on 1.8

- src/linting/checks.jl
- test/runtests.jl
Noticed this when writing a test for https://github.com/julia-vscode/LanguageServer.jl/pull/1048.
> Nothing comparison with ==/!=: also check LHS for nothing

- src/linting/checks.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/StaticLint.jl/issues/337.
> LoopOverLength check

- src/linting/checks.jl
- test/runtests.jl
to make "assigned but not used" annotation more correct.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2909.
> "Fix" is_overwritten_in_loop check

- src/interface.jl
17cca44b changed the fields of the FileServer struct without also changing the setup_server method. This fixes that and renames some variables to match the fields.
Fixes #358.
> Fix field mismatch in setup_server

- src/type_inf.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2639.
> fix(inf): improve type inference with destrcturing assignment

- src/linting/checks.jl
- test/runtests.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1244.
> fix: correctly follow find definitions for macros
